# Key things to remember is that factories should always provide a set of valid attributes, which means factories should always create a record with no validation errors
FactoryGirl.define do
  factory :campaign do
    # put the attr you want to assign as a variable/method
    # then put the value that you want the factory to assign to that attribute
    # if you type value without a block, it's going to be the same for all objects generated by the factory.
    # if you put it in a block, it will be executed every time.
    # to be 100% sure you need to use sequence to ensure no duplicity

    sequence(:name) { |n| "#{Faker::Company.bs}-#{n}" }
    sequence(:description){|n| "#{Faker::Lorem.paragraph}-#{n}" }
    goal          { ( 11 + Random.rand(1000)) }
    end_date      { 60.days.from_now }
  end

end
